# Required metadata
sonar.projectKey=gfb-easycredit-web
sonar.projectName=gfb-easycredit-web
sonar.projectVersion=1.0
sonar.sourceEncoding=UTF-8
sonar.language=js

# Path to source code
sonar.sources=src/components,src/pages,src/helpers,src/services,src/hooks

# Tests
sonar.tests=src/__tests__
sonar.test.inclusions=**/*.test.js,**/*.test.jsx

# Exclusions
sonar.exclusions=node_modules/**, .next/**, src/__mocks__/**
sonar.coverage.exclusions=src/pages/_app.js, src/pages/_document.js, src/pages/api/auth/*, src/components/Skeleton/*
sonar.cpd.exclusions=src/helpers/initials/*.js, src/components/model/**, src/components/Tables/**, src/components/Skeleton/**

# Coverage report
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.testExecutionReportPaths=test-report.xml
