const mockListLeaders = [
   {
      firstName: 'Test',
      secondName: 'User',
      firstSurname: 'Leader',
      secondSurname: 'One',
      userAD: 'testLC1',
      profile: 'LIDER DE CONTRAPARTE',
      idProfile: 4,
      acrProfile: 'LC',
      color: 'hsl(129,89%,38%)',
      commercialAddress: 'PROMOCIÓN REGIONAL NORTE',
      profileType: null,
      branchOffice: 'CORPORATIVO',
      zone: null,
      idZone: null,
      fullName: 'TEST USER LEADER ONE',
   },
   {
      firstName: 'Test',
      secondName: 'User',
      firstSurname: 'Leader',
      secondSurname: 'Two',
      userAD: 'testLC2',
      profile: 'LIDER DE CONTRAPARTE',
      idProfile: 4,
      acrProfile: 'LC',
      color: 'hsl(39, 91%, 27%)',
      commercialAddress: 'PROMOCIÓN REGIONAL NORTE',
      profileType: null,
      branchOffice: 'CORPORATIVO',
      zone: null,
      idZone: null,
      fullName: 'TEST USER LEADER TWO',
   },
   {
      firstName: 'Test',
      secondName: 'User',
      firstSurname: 'Leader',
      secondSurname: 'Three',
      userAD: 'testLC3',
      profile: 'LIDER DE CONTRAPARTE',
      idProfile: 4,
      acrProfile: 'LC',
      color: 'hsl(151, 71%, 33%)',
      commercialAddress: 'PROMOCIÓN REGIONAL MÉXICO',
      profileType: null,
      branchOffice: 'LOMAS',
      zone: 'NAC',
      idZone: null,
      fullName: 'TEST USER LEADER THREE',
   },
   {
      firstName: 'Test',
      secondName: 'User',
      firstSurname: 'Leader',
      secondSurname: 'Five',
      userAD: 'UserLDC',
      profile: 'LIDER DE CONTRAPARTE',
      idProfile: 4,
      acrProfile: 'LC',
      color: 'hsl(151, 71%, 33%)',
      commercialAddress: 'PROMOCIÓN REGIONAL MÉXICO',
      profileType: null,
      branchOffice: 'LOMAS',
      zone: 'NAC',
      idZone: null,
      fullName: 'USER TEST LDC',
   },
];

module.exports = mockListLeaders;
