const mockRequestNoChangeFinancials = {
   status: 200,
   data: [
      {
         approvedAmount: 2000,
         arrivedAcDate: '2025-06-03T08:46:12',
         arrivedLcDate: '2025-06-03T08:45:09',
         arrivedMrDate: '2025-06-03T08:40:32',
         arrivedSecDate: null,
         branchOffice: 'CORPORATIVO',
         createDate: '2025-06-03T08:37:49',
         groupName: 'TEST S.A. DE C.V.',
         idAnalyst: 'test',
         idCatTypeProcedure: 3,
         idCatStatus: 5,
         idGroup: 1,
         modifyDate: '2025-08-22T13:46:35',
         nameEmg: 'Unit Test ',
         oldStatus: 4,
         requestAmount: 3000,
         sendOtherProfile: false,
         totalPages: 1,
         userCreate: 'test',
         userModify: 'test',
         requestResponseList: [
            {
               alerts: null,
               amountSuggestC: null,
               amountSuggestEm: null,
               approvedAmount: 2000,
               commentAc: 'recomendacion',
               commentLc: null,
               coverComplete: true,
               createDate: '2025-06-03T08:37:49',
               currency: 'MXP',
               deleted: 0,
               endDate: null,
               hasVerification: false,
               idCatStatus: 5,
               idCatTypeProcedure: 3,
               idGroupRequest: 158,
               idRequest: 249,
               kindProcedure: 'Nuevo Tramite',
               lastDateExecEm: '2025-06-03T08:55:07',
               notional: '120',
               recommendationAc: true,
               recommendationLc: true,
               requestAmount: 3000000,
               resultExecEm: false,
               userCreate: 'test',
               userModify: 'test',
               relatedPersonResponseList: [
                  {
                     alternativeMail: null,
                     checkListComplete: false,
                     confirmInfoBureau: true,
                     deleted: false,
                     errorBureau: '',
                     fullName: 'TEST S.A. DE C.V.',
                     folioBureau: '',
                     idCatTypePerson: 1,
                     idClient: '11111',
                     idClientRelated: null,
                     idRelatedPerson: 2,
                     idRequest: 1,
                     mail: null,
                     maritalStatus: null,
                     personType: 'PM',
                     rfc: 'FFFFFFFFFF',
                     userCreate: 'test',
                     userModify: 'test',
                     lastDateBureau: '2025-06-03T08:41:44',
                     financialDocsChanges: false,
                     legalRepresentatives: [],
                  },
               ],
            },
         ],
      },
   ],
};

const mockRequestChangeFinancials = {
   status: 200,
   data: [
      {
         approvedAmount: null,
         arrivedAcDate: '2024-04-08',
         arrivedLcDate: '2024-04-08',
         arrivedMrDate: '2024-04-08',
         arrivedSecDate: null,
         branchOffice: null,
         createDate: '2024-03-21T13:13:16',
         groupName: 'Test group 1',
         idAnalyst: 'testuser1',
         idCatTypeProcedure: 3,
         idCatStatus: 3,
         idGroup: 1,
         isGroup:false,
         modifyDate: '2024-04-09T17:25:07',
         nameEmg: 'Test emg',
         oldStatus: 4,
         requestAmount: 10500000,
         sendOtherProfile: false,
         totalPages: 1,
         userCreate: 'testuser',
         userModify: 'testuser',
         requestResponseList: [
            {
               alerts: null,
               amountSuggestC: null,
               amountSuggestEm: null,
               approvedAmount: null,
               commentAc: null,
               commentLc: null,
               coverComplete: false,
               createDate: '2024-01-01T13:13:16',
               currency: 'MXP',
               deleted: 0,
               endDate: null,
               hasVerification: true,
               idCatStatus: 3,
               idCatTypeProcedure: 3,
               idGroupRequest: 1,
               idRequest: 1,
               kindProcedure: 'Nuevo Tramite',
               lastDateExecEm: '2024-04-05T16:45:26',
               notional: '6375922',
               recommendationAc: null,
               recommendationLc: null,
               requestAmount: 10500000,
               resultExecEm: true,
               userCreate: 'testuser',
               userModify: 'testuser',
               relatedPersonResponseList: [
                  {
                     alternativeMail: null,
                     checkListComplete: false,
                     confirmInfoBureau: null,
                     deleted: false,
                     errorBureau: null,
                     fullName: 'Test related person 1',
                     folioBureau: null,
                     idCatTypePerson: 1,
                     idClient: '163390',
                     idClientRelated: null,
                     idRelatedPerson: 1,
                     idRequest: 1,
                     mail: null,
                     maritalStatus: null,
                     personType: 'PM',
                     rfc: null,
                     userCreate: 'testuser',
                     userModify: 'testuser',
                     lastDateBureau: null,
                     financialDocsChanges: true,
                     legalRepresentatives: [],
                  },
               ],
            },
         ],
      },
      {
         approvedAmount: null,
         arrivedAcDate: '2024-04-08',
         arrivedLcDate: '2024-04-08',
         arrivedMrDate: '2024-04-08',
         arrivedSecDate: null,
         branchOffice: null,
         createDate: '2024-03-21T13:13:16',
         groupName: 'Test group 2',
         idAnalyst: 'testuser1',
         idCatTypeProcedure: 3,
         idCatStatus: 3,
         idGroup: 2,
         isGroup:false,
         modifyDate: '2024-04-09T17:25:07',
         nameEmg: 'Test emg',
         oldStatus: 4,
         requestAmount: 10500000,
         sendOtherProfile: false,
         totalPages: 1,
         userCreate: 'testuser',
         userModify: 'testuser',
         requestResponseList: [
            {
               alerts: null,
               amountSuggestC: null,
               amountSuggestEm: null,
               approvedAmount: null,
               commentAc: null,
               commentLc: null,
               coverComplete: false,
               createDate: '2024-01-01T13:13:16',
               currency: 'MXP',
               deleted: 0,
               endDate: null,
               hasVerification: true,
               idCatStatus: 3,
               idCatTypeProcedure: 3,
               idGroupRequest: 1,
               idRequest: 2,
               kindProcedure: 'Nuevo Tramite',
               lastDateExecEm: null,
               notional: '6375924.509053813',
               recommendationAc: null,
               recommendationLc: null,
               requestAmount: 10500000,
               resultExecEm: true,
               userCreate: 'testuser',
               userModify: 'testuser',
               relatedPersonResponseList: [
                  {
                     alternativeMail: null,
                     checkListComplete: false,
                     confirmInfoBureau: null,
                     deleted: false,
                     errorBureau: null,
                     fullName: 'Test related person 1',
                     folioBureau: null,
                     idCatTypePerson: 1,
                     idClient: '163390',
                     idClientRelated: null,
                     idRelatedPerson: 1,
                     idRequest: 1,
                     mail: null,
                     maritalStatus: null,
                     personType: 'PM',
                     rfc: null,
                     userCreate: 'testuser',
                     userModify: 'testuser',
                     lastDateBureau: null,
                     financialDocsChanges: true,
                     legalRepresentatives: [],
                  },
               ],
            },
         ],
      },
      {
         approvedAmount: null,
         arrivedAcDate: '2024-04-08',
         arrivedLcDate: '2024-04-08',
         arrivedMrDate: '2024-04-08',
         arrivedSecDate: null,
         branchOffice: null,
         createDate: '2024-03-21T13:13:16',
         groupName: 'Test group 3',
         idAnalyst: 'testuser2',
         idCatTypeProcedure: 3,
         idCatStatus: 3,
         idGroup: 3,
         isGroup:false,
         modifyDate: '2024-04-09T17:25:07',
         nameEmg: 'Test emg',
         oldStatus: 4,
         requestAmount: 10500000,
         sendOtherProfile: false,
         totalPages: 1,
         userCreate: 'testuser',
         userModify: 'testuser',
         requestResponseList: [
            {
               alerts: null,
               amountSuggestC: null,
               amountSuggestEm: null,
               approvedAmount: null,
               commentAc: null,
               commentLc: null,
               coverComplete: false,
               createDate: '2024-01-01T13:13:16',
               currency: 'MXP',
               deleted: 0,
               endDate: null,
               hasVerification: true,
               idCatStatus: 3,
               idCatTypeProcedure: 3,
               idGroupRequest: 1,
               idRequest: 3,
               kindProcedure: 'Nuevo Tramite',
               lastDateExecEm: null,
               notional: '6375924.509053813',
               recommendationAc: null,
               recommendationLc: null,
               requestAmount: 10500000,
               resultExecEm: true,
               userCreate: 'testuser',
               userModify: 'testuser',
               relatedPersonResponseList: [
                  {
                     alternativeMail: null,
                     checkListComplete: false,
                     confirmInfoBureau: null,
                     deleted: false,
                     errorBureau: null,
                     fullName: 'Test related person 1',
                     folioBureau: null,
                     idCatTypePerson: 1,
                     idClient: '163390',
                     idClientRelated: null,
                     idRelatedPerson: 1,
                     idRequest: 1,
                     mail: null,
                     maritalStatus: null,
                     personType: 'PM',
                     rfc: null,
                     userCreate: 'testuser',
                     userModify: 'testuser',
                     lastDateBureau: null,
                     financialDocsChanges: true,
                     legalRepresentatives: [],
                  },
               ],
            },
         ],
      },
      {
         approvedAmount: null,
         arrivedAcDate: '2024-04-08',
         arrivedLcDate: '2024-04-08',
         arrivedMrDate: '2024-04-08',
         arrivedSecDate: null,
         branchOffice: null,
         createDate: '2024-03-21T13:13:16',
         groupName: 'Test group 4',
         idAnalyst: null,
         idCatTypeProcedure: 3,
         idCatStatus: 3,
         idGroup: 4,
         isGroup:false,
         modifyDate: '2024-04-09T17:25:07',
         nameEmg: 'Test emg',
         oldStatus: 4,
         requestAmount: 10500000,
         sendOtherProfile: false,
         totalPages: 1,
         userCreate: 'testuser',
         userModify: 'testuser',
         requestResponseList: [
            {
               alerts: null,
               amountSuggestC: null,
               amountSuggestEm: null,
               approvedAmount: null,
               commentAc: null,
               commentLc: null,
               coverComplete: false,
               createDate: '2024-01-01T13:13:16',
               currency: 'MXP',
               deleted: 0,
               endDate: null,
               hasVerification: true,
               idCatStatus: 3,
               idCatTypeProcedure: 3,
               idGroupRequest: 1,
               idRequest: 4,
               kindProcedure: 'Nuevo Tramite',
               lastDateExecEm: null,
               notional: '6375924.509053813',
               recommendationAc: null,
               recommendationLc: null,
               requestAmount: 10500000,
               resultExecEm: true,
               userCreate: 'testuser',
               userModify: 'testuser',
               relatedPersonResponseList: [
                  {
                     alternativeMail: null,
                     checkListComplete: false,
                     confirmInfoBureau: null,
                     deleted: false,
                     errorBureau: null,
                     fullName: 'Test related person 1',
                     folioBureau: null,
                     idCatTypePerson: 1,
                     idClient: '163390',
                     idClientRelated: null,
                     idRelatedPerson: 1,
                     idRequest: 1,
                     mail: null,
                     maritalStatus: null,
                     personType: 'PM',
                     rfc: null,
                     userCreate: 'testuser',
                     userModify: 'testuser',
                     lastDateBureau: null,
                     financialDocsChanges: true,
                     legalRepresentatives: [],
                  },
               ],
            },
         ],
      },
   ],
};

module.exports = { mockRequestNoChangeFinancials, mockRequestChangeFinancials };
