export const constStates = {
   AGU: 'Aguascalientes',
   BCN: 'Baja California',
   BCS: 'Baja California Sur',
   CAM: 'Campeche',
   CHP: 'Chiapas',
   CHH: 'Chihuahua',
   CMX: 'Ciudad de México',
   COA: 'Coahuila',
   COL: 'Colima',
   DUR: 'Durango',
   GUA: 'Guanajuato',
   GRO: 'Guerrero',
   HID: 'Hidalgo',
   JAL: 'Jalisco',
   MEX: 'México',
   MIC: 'Michoacán',
   MOR: 'Morelos',
   NAY: 'Nayarit',
   NLE: 'Nuevo León',
   OAX: 'Oaxaca',
   PUE: 'Puebla',
   QUE: 'Querétaro',
   ROO: 'Quintana Roo',
   SLP: 'San Luis Potosí',
   SIN: 'Sinaloa',
   SON: 'Sonora',
   TAB: 'Tabasco',
   TAM: 'Tamaulipas',
   TLA: 'Tlaxcala',
   VER: 'Veracruz',
   YUC: 'Yucatán',
   ZAC: 'Zacatecas',
};

export const constCountrys = {
   AD: 'Andorra',
   AE: 'Emiratos Árabes Unidos',
   AF: 'Afganistán',
   AG: 'Antigua y Barbuda',
   AI: 'Anguila',
   AL: 'Albania',
   AM: 'Armenia',
   AO: 'Angola',
   AQ: 'Antártida',
   AR: 'Argentina',
   AS: 'Samoa Americana',
   AT: 'Austria',
   AU: 'Australia',
   AW: 'Aruba',
   AX: 'Islas Åland',
   AZ: 'Azerbaiyán',
   BA: 'Bosnia y Herzegovina',
   BB: 'Barbados',
   BD: 'Bangladés',
   BE: 'Bélgica',
   BF: 'Burkina Faso',
   BG: 'Bulgaria',
   BH: 'Baréin',
   BI: 'Burundi',
   BJ: 'Benín',
   BL: 'San Bartolomé',
   BM: 'Bermudas',
   BN: 'Brunéi',
   BO: 'Bolivia',
   BQ: 'Caribe neerlandés',
   BR: 'Brasil',
   BS: 'Bahamas',
   BT: 'Bután',
   BV: 'Isla Bouvet',
   BW: 'Botsuana',
   BY: 'Bielorrusia',
   BZ: 'Belice',
   CA: 'Canadá',
   CC: 'Islas Cocos',
   CD: 'República Democrática del Congo',
   CF: 'República Centroafricana',
   CG: 'Congo',
   CH: 'Suiza',
   CI: 'Costa de Marfil',
   CK: 'Islas Cook',
   CL: 'Chile',
   CM: 'Camerún',
   CN: 'China',
   CO: 'Colombia',
   CR: 'Costa Rica',
   CU: 'Cuba',
   CV: 'Cabo Verde',
   CW: 'Curazao',
   CX: 'Isla de Navidad',
   CY: 'Chipre',
   CZ: 'Chequia',
   DE: 'Alemania',
   DJ: 'Yibuti',
   DK: 'Dinamarca',
   DM: 'Dominica',
   DO: 'República Dominicana',
   DZ: 'Argelia',
   EC: 'Ecuador',
   EE: 'Estonia',
   EG: 'Egipto',
   EH: 'Sahara Occidental',
   ER: 'Eritrea',
   ES: 'España',
   ET: 'Etiopía',
   FI: 'Finlandia',
   FJ: 'Fiyi',
   FK: 'Islas Malvinas',
   FM: 'Micronesia',
   FO: 'Islas Feroe',
   FR: 'Francia',
   GA: 'Gabón',
   GB: 'Reino Unido',
   GD: 'Granada',
   GE: 'Georgia',
   GF: 'Guayana Francesa',
   GG: 'Guernsey',
   GH: 'Ghana',
   GI: 'Gibraltar',
   GL: 'Groenlandia',
   GM: 'Gambia',
   GN: 'Guinea',
   GP: 'Guadalupe',
   GQ: 'Guinea Ecuatorial',
   GR: 'Grecia',
   GS: 'Islas Georgia del Sur y Sandwich del Sur',
   GT: 'Guatemala',
   GU: 'Guam',
   GW: 'Guinea-Bissau',
   GY: 'Guyana',
   HK: 'Hong Kong',
   HM: 'Islas Heard y McDonald',
   HN: 'Honduras',
   HR: 'Croacia',
   HT: 'Haití',
   HU: 'Hungría',
   ID: 'Indonesia',
   IE: 'Irlanda',
   IL: 'Israel',
   IM: 'Isla de Man',
   IN: 'India',
   IO: 'Territorio Británico del Océano Índico',
   IQ: 'Irak',
   IR: 'Irán',
   IS: 'Islandia',
   IT: 'Italia',
   JE: 'Jersey',
   JM: 'Jamaica',
   JO: 'Jordania',
   JP: 'Japón',
   KE: 'Kenia',
   KG: 'Kirguistán',
   KH: 'Camboya',
   KI: 'Kiribati',
   KM: 'Comoras',
   KN: 'San Cristóbal y Nieves',
   KP: 'Corea del Norte',
   KR: 'Corea del Sur',
   KW: 'Kuwait',
   KY: 'Islas Caimán',
   KZ: 'Kazajistán',
   LA: 'Laos',
   LB: 'Líbano',
   LC: 'Santa Lucía',
   LI: 'Liechtenstein',
   LK: 'Sri Lanka',
   LR: 'Liberia',
   LS: 'Lesoto',
   LT: 'Lituania',
   LU: 'Luxemburgo',
   LV: 'Letonia',
   LY: 'Libia',
   MA: 'Marruecos',
   MC: 'Mónaco',
   MD: 'Moldavia',
   ME: 'Montenegro',
   MF: 'San Martín',
   MG: 'Madagascar',
   MH: 'Islas Marshall',
   MK: 'Macedonia del Norte',
   ML: 'Mali',
   MM: 'Birmania',
   MN: 'Mongolia',
   MO: 'Macao',
   MP: 'Islas Marianas del Norte',
   MQ: 'Martinica',
   MR: 'Mauritania',
   MS: 'Montserrat',
   MT: 'Malta',
   MU: 'Mauricio',
   MV: 'Maldivas',
   MW: 'Malaui',
   MX: 'México',
   MY: 'Malasia',
   MZ: 'Mozambique',
   NA: 'Namibia',
   NC: 'Nueva Caledonia',
   NE: 'Níger',
   NF: 'Isla Norfolk',
   NG: 'Nigeria',
   NI: 'Nicaragua',
   NL: 'Países Bajos',
   NO: 'Noruega',
   NP: 'Nepal',
   NR: 'Nauru',
   NU: 'Niue',
   NZ: 'Nueva Zelanda',
   OM: 'Omán',
   PA: 'Panamá',
   PE: 'Perú',
   PF: 'Polinesia Francesa',
   PG: 'Papúa Nueva Guinea',
   PH: 'Filipinas',
   PK: 'Pakistán',
   PL: 'Polonia',
   PM: 'San Pedro y Miquelón',
   PN: 'Islas Pitcairn',
   PR: 'Puerto Rico',
   PS: 'Palestina',
   PT: 'Portugal',
   PW: 'Palaos',
   PY: 'Paraguay',
   QA: 'Catar',
   RE: 'Reunión',
   RO: 'Rumania',
   RS: 'Serbia',
   RU: 'Rusia',
   RW: 'Ruanda',
   SA: 'Arabia Saudita',
   SB: 'Islas Salomón',
   SC: 'Seychelles',
   SD: 'Sudán',
   SE: 'Suecia',
   SG: 'Singapur',
   SH: 'Santa Elena',
   SI: 'Eslovenia',
   SJ: 'Svalbard y Jan Mayen',
   SK: 'Eslovaquia',
   SL: 'Sierra Leona',
   SM: 'San Marino',
   SN: 'Senegal',
   SO: 'Somalia',
   SR: 'Surinam',
   SS: 'Sudán del Sur',
   ST: 'Santo Tomé y Príncipe',
   SV: 'El Salvador',
   SX: 'Sint Maarten',
   SY: 'Siria',
   SZ: 'Suazilandia',
   TC: 'Islas Turcas y Caicos',
   TD: 'Chad',
   TF: 'Territorios Australes Franceses',
   TG: 'Togo',
   TH: 'Tailandia',
   TJ: 'Tayikistán',
   TK: 'Tokelau',
   TL: 'Timor Oriental',
   TM: 'Turkmenistán',
   TN: 'Túnez',
   TO: 'Tonga',
   TR: 'Turquía',
   TT: 'Trinidad y Tobago',
   TV: 'Tuvalu',
   TW: 'Taiwán',
   TZ: 'Tanzania',
   UA: 'Ucrania',
   UG: 'Uganda',
   UM: 'Islas menores alejadas de los Estados Unidos',
   US: 'Estados Unidos',
   UY: 'Uruguay',
   UZ: 'Uzbekistán',
   VA: 'Ciudad del Vaticano',
   VC: 'San Vicente y las Granadinas',
   VE: 'Venezuela',
   VG: 'Islas Vírgenes Británicas',
   VI: 'Islas Vírgenes de los Estados Unidos',
   VN: 'Vietnam',
   VU: 'Vanuatu',
   WF: 'Wallis y Futuna',
   WS: 'Samoa',
   YE: 'Yemen',
   YT: 'Mayotte',
   ZA: 'Sudáfrica',
   ZM: 'Zambia',
   ZW: 'Zimbabue',
};

export const catStatus = {
   1: 'En proceso',
   2: 'En validación por mesa receptora de crédito',
   3: 'En asignación por líder de contraparte',
   4: 'En análisis de contraparte',
   5: 'En revisión del estudio por líder de contraparte',
   6: 'En revisión con Secretariado',
   7: 'Devuelta por Mesa Receptora de Crédito',
   8: 'Devuelta a EMG por líder de contraparte',
   9: 'Devuelta a EMG por analista',
   10: 'Autorizada',
   11: 'No Aprobada',
   12: 'Finalizada',
   13: 'Pendiente Perfil Cliente',
   14: 'Incompleto Perfil Cliente',
   15: 'Finalizado Perfil Cliente',
   16: 'Pendiente Relacion Propiedades',
   17: 'Incompleto Relacion Propiedades',
   18: 'Finalizado Relacion Propiedades',
   19: 'Pendiente',
   20: 'Incompleto',
   21: 'Finalizado',
   22: 'Devuelta a analista por líder de contraparte',
   23: 'Cancelada',
   24: 'Cancelada por embargo',
   25: 'Finalizado Relacion Propiedades',
   26: 'En revisión con Facultado',
};

export const constProfiles = {
   ADC: 1,
   MRC: 2,
   EMG: 3,
   LDC: 4,
   SEC: 5,
   FAC: 6,
};

export const constNextProfileAndStatus = {
   1: { nextProfile: 'MR', nextStatus: 2, msg: 'La solicitud ha pasado a Mesa Receptora' },
   3: { nextProfile: 'AC', nextStatus: 4, msg: 'La solicitud se ha enviado al Analista' },
   4: { nextProfile: 'LC', nextStatus: 5, msg: 'La solicitud se ha enviado al Líder' },
   7: { nextProfile: 'MR', nextStatus: 2, msg: 'La solicitud se ha devuelto a Mesa Receptora' },
   8: { nextProfile: 'LC', nextStatus: 3, msg: 'La solicitud se ha devuelto a Líder' },
   9: { nextProfile: 'AC', nextStatus: 4, msg: 'La solicitud se ha devuelto a Analista' },
};

export const constPageProcessType = {
   CREATE_REQUEST: 1,
   SAVE_OBLIGED: 2,
   GET_CHECKLIST: 3,
   SAVE_COVERAGE: 4,
   SAVE_CAL_RATE: 5,
   SAVE_CALC_EXCHANGE: 6,
   SAVE_PROFILE: 7,
   SAVE_RELATIONSHIP: 8,
};

export const constTypePerson = {
   1: 'APPLICANT',
   2: 'SOLIDARY_OBLIGED',
   3: 'LEGAL_REPRESENTIVE',
   APPLICANT: 1,
   SOLIDARY_OBLIGED: 2,
   LEGAL_REPRESENTATIVE: 3,
};

export const constMonths = [
   'Enero',
   'Febrero',
   'Marzo',
   'Abril',
   'Mayo',
   'Junio',
   'Julio',
   'Agosto',
   'Septiembre',
   'Octubre',
   'Noviembre',
   'Diciembre',
];

export const constRequestLifeStatus = {
   finish: [10, 11, 12, 23, 24],
   substatus: [2, 3, 4, 5, 6, 7, 8, 9, 22],
};

export const constSnackbarColors = {
   confirm: '#064bb5', //* Azul
   success: '#27996c', //* Verde
   error: '#ff6265', //* Rojo
};

export const EnumStatus = {
   EN_ESPECIALISTA_FINANCIAMIENTO: 1,
   EN_MESA_RECEPTORA: 2,
   EN_ASIGNACION_LIDER: 3,
   EN_ANALISTA: 4,
   EN_REVISION_LIDER: 5,
   EN_RESOLUCION_SECRETARIADO: 6,
   DEVUELTA_EF_POR_MESA: 7,
   DEVUELTA_EF_POR_LIDER: 8,
   DEVUELTA_EF_POR_ANALISTA: 9,
   SOLICITUD_AUTORIZADA: 10,
   SOLICITUD_RECHAZADA: 11,
   SOLICITUD_FINALIZADA: 12,
   DEVUELTA_ANALISTA_POR_LIDER: 22,
   SOLICITUD_CANCELADA: 23,
   SOLICITUD_CANCELADA_POR_EMBARGO: 24,
   FORMATO_CONGELADO: 25,
   EN_REVISION_FACULTADO: 26,
};

export const EnumTypesHistoryForProfile = {
   5: 'SEC_HISTORY',
   6: 'FAC_HISTORY',
};

export const EnumTypeChats = {
   SAVE_CHAT: 'SAVE_CHAT',
   SAVE_RESPONSE: 'SAVE_RESPONSE',
   DELETE_CHAT: 'DELETE_CHAT_ALL',
   DELETE_RESPONSE: 'DELETE_RESPONSE',
};

export const EnumTypeMessage = {
   INFORMATION: 'INFORMATION',
};

export const EnumStatusForGraph = {
   TRACKING_PAGE: '2,3,4,5,6,7,8,9,12,22,23,24,26',
   LEADER_REQUESTS_PAGE: '3, 4, 5, 6, 8, 9, 22, 26',
};

export const mapRoutePages = {
   GO_TO_REQUESTS_PAGE: (path) => `/${path}/RequestsReview`,
   GO_TO_REQUEST_DETAILS_PAGE: (path, idGroup) => `/${path}/RequestsReview/${idGroup}`,
   GO_TO_HISTORY: () => `/Shared/History`,
   GO_TO_HISTORY_DETAILS: (idParam) => `/Shared/History/${idParam}`,
   GO_TO_SOLIDARY_PAGE: (idGroup) => `/EMG/Solidary/${idGroup}`,
   GO_TO_GENERAL_INFORMATION_PAGE: (idGroup) => `/EMG/GeneralInformation/${idGroup}`,
   GO_TO_CHECKLIST_PAGE: (idGroup, path) => `/${path}/Documentation/${idGroup}`,
   GO_TO_PROPERTIES_PAGE: (idRequest, idGroup) => `/Shared/PropertyVerification/${idRequest}?idGroup=${idGroup}`,
   GO_TO_PCD_PAGE: (path, idRequest, idGroup) => `/${path}/PCD/${idRequest}?idGroup=${idGroup}`,
   GO_TO_VALIDATION_REQUEST_PAGE: (idGroup) => `/MRC/ValidateRequest/${idGroup}`,
   GO_TO_BURO_VALIDATION_PAGE: (idClient, idRequest, idGroup) =>
      `/MRC/BuroValidation/${idClient}?idRequest=${idRequest}&idGroup=${idGroup}`,
   GO_TO_GENERAL_BALANCE_PAGE: (idRequest, idGroup, rfc, idClient) =>
      `/Shared/GeneralBalance/${idRequest}?idGroup=${idGroup}&rfc=${rfc}&idClient=${idClient}`,
   GO_TO_RESULTS_STATES_PAGE: (idRequest, idGroup, rfc, idClient) =>
      `/Shared/StateResults/${idRequest}?idGroup=${idGroup}&rfc=${rfc}&idClient=${idClient}`,
   GO_TO_RETURN_REQUEST_PAGE: (path, idGroup, origin) => `/${path}/ReturnRequest/${idGroup}?origin=${origin}`,
   GO_TO_APPLICATION_EVALUATION_PAGE: (path, idGroup) => `/${path}/ApplicationEvaluation/${idGroup}`,
   GO_TO_MODEL_PAGE: (idGroup) => `/Shared/Model/${idGroup}`,
   GO_TO_COVER_PAGE: (path, idGroup) => `/${path}/Cover/${idGroup}`,
   GO_TO_RECOMENDATION_PAGE: (path, idGroup) => `/${path}/Recomendation/${idGroup}`,
};

export const mapIconForStatus = {
   10: {
      icon: 'check_circle',
      color: 'text-emerald-500',
   },
   11: {
      icon: 'cancel',
      color: 'text-red-500',
   },
};
