export const tooltipMessages = {
   1: 'Ingresos netos',
   6: 'Intereses devengados a cargo del nacionales_Partes no relacionadas +\n\nIntereses devengados a cargo del nacionales_Partes relacionadas +\n\nIntereses devengados a cargo del extranjero_Partes no relacionadas +\n\nIntereses devengados a cargo del extranjero_Partes relacionadas +\n\nInteres moratorios a cargo del nacionales_Partes no relacionadas +\n\nIntereses moratorios a cargo del nacionales_Partes relacionadas +\n\nIntereses moratorios a cargo del extranjero_Partes no relacionadas +\n\nIntereses moratorios a cargo del extranjero_Partes relacionadas',
   14: 'ISR',
   7: 'Depreciación contable = Depreciación_acumulada[Año final] -\nDepreciación acumulada[Año anterior]. \n\nAmortización contable =  Amortización_acumulada[Año final] -\nAmortización acumulada [Año anterior].',
   8: 'Depreciación contable = Depreciación_acumulada[Año final] -\nDepreciación acumulada[Año anterior]. \n\nAmortización contable =  Amortización_acumulada[Año final] -\nAmortización acumulada [Año anterior].',
};

export const constSR = {
   automatic: ['3', '5'],
   toolTip: ['1', '6', '14'],
};

export const stateResults = {
   dateElaboration: '',
   fullName: '',
   idCatTypePerson: '',
   idClient: '',
   idRequest: '',
   rfc: '',
   status: '',
   periods: [
      {
         month: 'December',
         monthIncludes: 0,
         officeOrAccountant: '',
         periodType: 'ANNUAL',
         sourceInformation: '',
         year: 2022,
         concepts: [
            {
               description: 'Ventas Netas',
               id: '1',
               amount: '0',
               percentage: '0',
               automatic: false,
               focus: false,
            },
            {
               description: 'Costo de ventas y/o servicios',
               id: '2',
               amount: '0',
               percentage: '0',
               automatic: false,
               focus: false,
            },
            {
               description: 'Utilidad Bruta',
               id: '3',
               amount: '0',
               percentage: '0',
               automatic: true,
               focus: false,
            },
            {
               description: 'Gastos de Operación',
               id: '4',
               amount: '0',
               percentage: '0',
               automatic: false,
               focus: false,
            },
            {
               description: 'Utilidad de Operación',
               id: '5',
               amount: '0',
               percentage: '0',
               automatic: true,
               focus: false,
            },
            {
               description: 'Interés Pagado',
               id: '6',
               amount: '0',
               percentage: '0',
               automatic: false,
               focus: false,
            },
            {
               description: 'Impuestos',
               id: '14',
               amount: '0',
               percentage: '0',
               automatic: false,
               focus: false,
            },
         ],
         depreciationSchedule: [
            {
               description: 'Depreciación y amortización',
               id: '21',
               amount: '0',
               percentage: '0',
               automatic: false,
               focus: false,
            },
         ],
         analyseOperating: [
            {
               description: 'Ventas y/o servicios nacionales netas',
               id: '23',
               amount: '0',
               percentage: '0',
               automatic: false,
               focus: false,
            },
            {
               description: 'Ventas y/o servicios extranjeros netas',
               id: '24',
               amount: '0',
               percentage: '0',
               automatic: false,
               focus: false,
            },
            {
               description: 'Compras netas nacionales',
               id: '25',
               amount: '0',
               percentage: '0',
               automatic: false,
               focus: false,
            },
            {
               description: 'Compras netas de importación',
               id: '26',
               amount: '0',
               percentage: '0',
               automatic: false,
               focus: false,
            },
         ],
      },
      {
         month: 'December',
         monthIncludes: 0,
         officeOrAccountant: '',
         periodType: 'ANNUAL',
         sourceInformation: '',
         year: 2022,
         concepts: [
            {
               description: 'Ventas Netas',
               id: '1',
               amount: '0',
               percentage: '0',
               automatic: false,
               focus: false,
            },
            {
               description: 'Costo de ventas y/o servicios',
               id: '2',
               amount: '0',
               percentage: '0',
               automatic: false,
               focus: false,
            },
            {
               description: 'Utilidad Bruta',
               id: '3',
               amount: '0',
               percentage: '0',
               automatic: true,
               focus: false,
            },
            {
               description: 'Gastos de Operación',
               id: '4',
               amount: '0',
               percentage: '0',
               automatic: false,
               focus: false,
            },
            {
               description: 'Utilidad de Operación',
               id: '5',
               amount: '0',
               percentage: '0',
               automatic: true,
               focus: false,
            },
            {
               description: 'Interés Pagado',
               id: '6',
               amount: '0',
               percentage: '0',
               automatic: false,
               focus: false,
            },
            {
               description: 'Impuestos',
               id: '14',
               amount: '0',
               percentage: '0',
               automatic: false,
               focus: false,
            },
         ],
         depreciationSchedule: [
            {
               description: 'Depreciación y amortización',
               id: '21',
               amount: '0',
               percentage: '0',
               automatic: false,
               focus: false,
            },
         ],
         analyseOperating: [
            {
               description: 'Ventas y/o servicios nacionales netas',
               id: '23',
               amount: '0',
               percentage: '0',
               automatic: false,
               focus: false,
            },
            {
               description: 'Ventas y/o servicios extranjeros netas',
               id: '24',
               amount: '0',
               percentage: '0',
               automatic: false,
               focus: false,
            },
            {
               description: 'Compras netas nacionales',
               id: '25',
               amount: '0',
               percentage: '0',
               automatic: false,
               focus: false,
            },
            {
               description: 'Compras netas de importación',
               id: '26',
               amount: '0',
               percentage: '0',
               automatic: false,
               focus: false,
            },
         ],
      },
      {
         month: 'February',
         monthIncludes: 0,
         officeOrAccountant: '',
         periodType: 'PARTIAL',
         sourceInformation: '',
         year: 2023,
         concepts: [
            {
               description: 'Ventas Netas',
               id: '1',
               amount: '0',
               percentage: '0',
               automatic: false,
               focus: false,
            },
            {
               description: 'Costo de ventas y/o servicios',
               id: '2',
               amount: '0',
               percentage: '0',
               automatic: false,
               focus: false,
            },
            {
               description: 'Utilidad Bruta',
               id: '3',
               amount: '0',
               percentage: '0',
               automatic: true,
               focus: false,
            },
            {
               description: 'Gastos de Operación',
               id: '4',
               amount: '0',
               percentage: '0',
               automatic: false,
               focus: false,
            },
            {
               description: 'Utilidad de Operación',
               id: '5',
               amount: '0',
               percentage: '0',
               automatic: true,
               focus: false,
            },
            {
               description: 'Interés Pagado',
               id: '6',
               amount: '0',
               percentage: '0',
               automatic: false,
               focus: false,
            },
            {
               description: 'Impuestos',
               id: '14',
               amount: '0',
               percentage: '0',
               automatic: false,
               focus: false,
            },
         ],
         depreciationSchedule: [
            {
               description: 'Depreciación y amortización',
               id: '21',
               amount: '0',
               percentage: '0',
               automatic: false,
               focus: false,
            },
         ],
         analyseOperating: [
            {
               description: 'Ventas y/o servicios nacionales netas',
               id: '23',
               amount: '0',
               percentage: '0',
               automatic: false,
               focus: false,
            },
            {
               description: 'Ventas y/o servicios extranjeros netas',
               id: '24',
               amount: '0',
               percentage: '0',
               automatic: false,
               focus: false,
            },
            {
               description: 'Compras netas nacionales',
               id: '25',
               amount: '0',
               percentage: '0',
               automatic: false,
               focus: false,
            },
            {
               description: 'Compras netas de importación',
               id: '26',
               amount: '0',
               percentage: '0',
               automatic: false,
               focus: false,
            },
         ],
      },
   ],
};

export const constConceptsSR = {
   VENTAS_NETAS: '1',
   COSTO_DE_VENTAS_Y_O_SERVICIO: '2',
   UTILIDAD_BRUTA: '3',
   GASTOS_DE_OPERACION: '4',
   UTILIDAD_DE_OPERACION: '5',
   INTERES_PAGADO: '6',
   IMPUESTOS: '14',
};

export const constDepreciationSR = {
   DEPRECIACION_Y_AMORTIZACION: '21',
};

export const constAnalyseOperatingSR = {
   VENTAS_SERVICIOS_NACIONALES_NETAS: '23',
   VENTAS_SERVICIOS_EXTRANJEROS_NETAS: '24',
   COMPRAS_NETAS_NACIONALES: '25',
   COMPRAS_NETAS_DE_IMPORTACION: '26',
};
